#include<iostream>
using namespace std;
int main() {
  int a, b, c, d, e, f, g, h, i, j;
  cin >> a >> b >> c >> d >> e >> f >> g >> h >> i >> j;
  if (a > b) swap(a, b);
  if (a > c) swap(a, c);
  if (a > d) swap(a, d);
  if (a > e) swap(a, e);
  if (a > f) swap(a, f);
  if (a > g) swap(a, g);
  if (a > h) swap(a, h);
  if (a > i) swap(a, i);
  if (a > j) swap(a, j);
  if (b > c) swap(b, c);
  if (b > d) swap(b, d);
  if (b > e) swap(b, e);
  if (b > f) swap(b, f);
  if (b > g) swap(b, g);
  if (b > h) swap(b, h);
  if (b > i) swap(b, i);
  if (b > j) swap(b, j);
  if (c > d) swap(c, d);
  if (c > e) swap(c, e);
  if (c > f) swap(c, f);
  if (c > g) swap(c, g);
  if (c > h) swap(c, h);
  if (c > i) swap(c, i);
  if (c > j) swap(c, j);
  if (d > e) swap(d, e);
  if (d > f) swap(d, f);
  if (d > g) swap(d, g);
  if (d > h) swap(d, h);
  if (d > i) swap(d, i);
  if (d > j) swap(d, j);
  if (e > f) swap(e, f);
  if (e > g) swap(e, g);
  if (e > h) swap(e, h);
  if (e > i) swap(e, i);
  if (e > j) swap(e, j);
  if (f > g) swap(f, g);
  if (f > h) swap(f, h);
  if (f > i) swap(f, i);
  if (f > j) swap(f, j);
  if (g > h) swap(g, h);
  if (g > i) swap(g, i);
  if (g > j) swap(g, j);
  if (h > i) swap(h, i);
  if (h > j) swap(h, j);
  if (i > j) swap(i ,j);
  cout << a << " " << b << " " << c << " " << d << " " << e << " " << f << " " << g << " " << h << " " << i << " " << j << " " << endl; 
}
